### ISSUE TITLE
Consider implementing an importpack.js file for Soundboard

### ISSUE THREAD

**Issue by akrigline** [CDeenen/SoundFxLibrary#1]
Soundboard by Blitz has an api method which registers a "pack", [demoed here](https://github.com/BlitzKraig/fvtt-SoundBoard-BlitzCommunityPack/blob/master/importpack.js).

It would be a big boon to be able to keep an existing custom sounds directory but also use the ones bundled here, without having to copy and paste the sounds.

Data storage for Forge Users or other hosted plans is a concern which would be alleviated by such an integration.

**Comment by akrigline** [comment]
This is something I would open a PR for but I am not sure how best to navigate the license of this repository.

**Comment by CDeenen** [comment]
That sounds like a great idea. I don't use Soundboard by Blitz, so I don't know exactly how that would work.
Regarding the license issue:
I've just added a MIT license to the library itself, but of course that doesn't cover the included audio files.
Maybe it should be something like this:
```
licenses: [{
    licenseUrl: 'https://github.com/CDeenen/SoundFxLibrary/raw/master/Attribution.xlsx',
    licenseType: 'SoundFx Library',
    licenseDescription: 'License for each sound is found in Attribution.xlsx'
 }]
```

**Comment by CDeenen** [comment]
For Soundboard, you'd probably only want the single effects, not the loops, so maybe this library should be reorganized:
├─Single
│   ├──Nature
│   ├──Combat
│   └──Etc
├─Loops
│   ├──Nature
│   ├──Combat
│   └──Etc

**Comment by akrigline** [comment]
I think that Soundboard can handle loops, so it'll be alright as it is. I'll give things a test and report back though.

(I've only barely started understanding the nuances of single licenses, multiple licenses are definitely beyond me)

**Comment by akrigline** [comment]
Alright I just tried a basic registration and it definitely mostly works. The only folder that doesn't cooperate at the moment is Misc, which should have `Single` and `Loops` subdirectories to match the rest.

There's a certain degree of optimization that could be undergone with the Soundboard by Blitz in mind, but it would involve moving a lot of the files around, which isn't ideal.

Blitz's Soundboard lets you have wildcard sounds by putting a bunch of sounds in a directory within the registered directory.

E.g. Instead of having "Arrow Hit 1, 2, 3" and "Arrow flyby 1, 2, 3" It would be a blue "Arrow Hit" which when clicked on, would pick a random one to play.

![image](https://user-images.githubusercontent.com/7644614/121284449-de081800-c8aa-11eb-9c4a-33dc1e29223c.png)

Since you're not specifically targeting the Blitz Soundboard, making this shift might not be worth it, I think it's pretty reasonable to ask GMs interested in this option to DIY it.

As an aside, adding a registration to let Moulinette index these files was also delightfully simple.

**Comment by CDeenen** [comment]
Thanks for the PR!
I can work with your suggestion for the folder structure in my applications, so I'll change it.

**Comment by CDeenen** [comment]
FYI: I've pushed v1.0.1 with the new folder structure. It works perfectly in Soundboard now.
For Moulinette I had to separate each category into the 'single' and 'loops' packs, otherwise it wouldn't work properly. I think it doesn't work properly with so many subfolders. It now works fine.
